language: java
jdk:
  - oraclejdk10
before_script: 
  cd sonar-connector
addons:
  sonarcloud:
    organization: "thepracticaldeveloper"
    branches:
      - master
      - develop
script:
  - mvn clean install sonar:sonar
