language: java
jdk:
  - openjdk10

stages:
  - tests-sonar
  - docker-build
  - deploy

jobs:
  include:
  - stage: tests-sonar
    addons:
      sonarcloud:
        organization: "thepracticaldeveloper"
    before_script: cd sonar-connector
    script:
      - mvn clean install sonar:sonar
  - stage: docker-build
    sudo: required
    services: docker
    script: docker-compose -f docker-compose-build.yml build
  - stage: deploy
    script: echo "Deploying... (noop)"

