version: "3"

services:

  code-quality-game:
    build:
      context: ./sonar-connector
    image: code-quality-game
    ports:
      - "8080:8080"
    networks:
      - network1

  code-quality-game-ui:
    build:
      context: ./frontend
    image: code-quality-game-frontend
    ports:
      - "3000:3000"
    networks:
      - network1

networks:
  network1:
