version: "3"

services:

  code-quality-game:
    build:
      context: ./sonar-connector
    image: code-quality-game
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_HOST: mongo
    ports:
      - "8080:8080"
    networks:
      - network1

  mongo:
    image: mongo:3.4
    hostname: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - network1

  code-quality-game-ui:
    build:
      context: ./web-client
    image: code-quality-game-web-client
    ports:
      - "80:80"
    networks:
      - network1

networks:
  network1:
volumes:
  mongodata:
