sonar:
  server: https://sonarcloud.io
  organization: thepracticaldeveloper
  token:

game:
  dates:
    legacy: 2018-01-21
    earlyBird: 2018-01-30

spring:
  data:
    mongodb:
      database: code_quality_game

logging:
  level:
    com.thepracticaldeveloper.devgame: TRACE
