sonar:
  server: https://sonarcloud.io
  # If you specify organization, users will be filtered by those belonging to it.
  # This is useful when the server is shared (like SonarCloud). You must provide a token in that case.
  organization: thepracticaldeveloper
  token:

game:
  dates:
    legacy: 2018-01-21
    earlyBird: 2018-01-30
    campaignStart: 1970-01-01
  code:

spring:
  data:
    mongodb:
      database: code_quality_game

logging:
  level:
    com.thepracticaldeveloper.devgame: TRACE
